services:
  - type: web
    name: nike-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRETE_KEY
        sync: false
      - key: JWT_EXPIRE_IN
        value: 24h
      - key: EMAIL
        sync: false
      - key: PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        value: admin@nike.com
      - key: ADMIN_PASSWORD
        value: admin123
      - key: ADMIN_USERNAME
        value: admin
      - key: CLOUDINARY_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false 